#!/bin/bash

# Copyright            2012        Bryan Garber da Silva

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# Modify this var as needed.
RUBY=/usr/bin/ruby

if [ -n $RUBY ]; then
    $RUBY syncconf.rb $@
else
    echo "I haven't found Ruby. If you're sure that Ruby is installed, try" \
        "editing this Shell Script."
fi

